script:
  - npm test --single-run
  - node_modules/.bin/protractor e2e/conf.js --browser=firefox
language: node_js
node_js:
  - "0.10"
before_script:
  - "npm install"
  - "npm install grunt-cli"
  - "npm install grunt-contrib-jasmine"
  - "echo \"module.exports=function(grunt){grunt.initConfig({jasmine:{src:'src/**/*.js',options:{specs:'spec/**/*.js',keepRunner:false,vendor:['http://code.jquery.com/jquery-2.1.3.min.js','http://raw.githubusercontent.com/velesin/jasmine-jquery/master/lib/jasmine-jquery.js']}}});grunt.loadNpmTasks('grunt-contrib-jasmine');grunt.registerTask('default',['jasmine']);};\" > Gruntfile.js"
  - "bower install"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm start > /dev/null &"
  - "webdriver-manager update"
  - "sleep 3"
  #travis
