script:
  - npm test --single-run
  - node_modules/.bin/protractor e2e/conf.js --browser=chrome
language: node_js
node_js:
  - "0.12.7"
before_script:
  - bower install -g bower
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm start > /dev/null &
  - webdriver-manager update
  - sleep 3
